exclude: '^.*.csv$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      #   - id: end-of-file-fixer
      #   - id: trailing-whitespace
      #   - id: check-case-conflict
      #   - id: check-json
      #   - id: check-merge-conflict
      - id: requirements-txt-fixer
